export {
  Dashboard,
  TaskList,
  UserManagement,
  UserManagementForm,
  UserManagementDetails,
  MeetingLog,
  AddMeeting,
  MeetingDetail,
  ProjectInsights,
  LiveMap,
  TaskDetails,
  OngoingTask,
  OngoingTaskDetails,
} from "./admin";
