export {
  Dashboard,
  TaskList,
  UserManagement,
  UserManagementForm,
  UserManagementDetails,
  CreateTask,
  AddTask,
  TaskDetail,
  ProjectInsights,
  LiveMap,
  TaskDetails,
  OngoingTask,
  OngoingTaskDetails,
  CompletedTask,
  Payouts,
} from "./admin";
